# Generated by Django 2.1.7 on 2019-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='LastCommit',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='repository',
            name='LastConsultation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
