# Generated by Django 2.1 on 2018-08-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.PositiveSmallIntegerField()),
                ('repository', models.URLField(blank=True, max_length=100, null=True)),
                ('deploy_date', models.DateField()),
            ],
        ),
    ]
