# Generated by Django 2.1 on 2018-08-18 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0006_company_developer_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='devs.Company'),
        ),
        migrations.AddField(
            model_name='software',
            name='developer',
            field=models.ManyToManyField(to='devs.Developer'),
        ),
    ]
