# Generated by Django 2.1 on 2018-08-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0007_auto_20180817_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='developer',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
